version: 2

updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    labels:
      - dependencies
    reviewers:
      - souzagab

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    versioning-strategy: increase-if-necessary
    labels:
      - dependencies
    reviewers:
      - souzagab

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - ops
    reviewers:
      - souzagab

